# Generated by Django 4.2.13 on 2024-06-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_module_end_time_remove_module_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_allocated',
        ),
    ]
