# Generated by Django 4.2.13 on 2024-07-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_task_time_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='assistant_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='thread_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
