# Generated by Django 4.2.14 on 2024-07-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chatsession_accounts_ch_module__e0efa4_idx_and_more'),
        ('langchain_stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='accounts.chatsession'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['session'], name='langchain_s_session_8bd066_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['created_at'], name='langchain_s_created_fd6070_idx'),
        ),
    ]
