# Generated by Django 4.2.13 on 2024-06-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='assigned_students',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='instruction_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='persona_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_allocated',
            field=models.IntegerField(default=60),
        ),
    ]
