# Generated by Django 4.2.13 on 2024-06-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.task'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.module'),
        ),
    ]
