# Generated by Django 4.2.13 on 2024-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_chatsession_assistant_id_chatsession_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
