# Generated by Django 4.2.14 on 2024-07-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_module_content_module_files_task_files'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['module'], name='accounts_ch_module__e0efa4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['created_at'], name='accounts_ch_created_91cd04_idx'),
        ),
    ]
