# Generated by Django 4.2.14 on 2024-07-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chatsession_accounts_ch_module__e0efa4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interaction_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
