# Generated by Django 4.2.14 on 2024-07-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usercsvdownload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercsvdownload',
            name='module_id',
        ),
        migrations.AddField(
            model_name='usercsvdownload',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_module', to='accounts.module'),
        ),
    ]
