# Generated by Django 4.2.14 on 2024-07-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_usercsvdownload_module_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercsvdownload',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
