# Generated by Django 4.2.14 on 2024-07-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usercsvdownload_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interaction_mode',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_speed',
            field=models.FloatField(default=1.0),
        ),
    ]
