# Generated by Django 4.2.14 on 2024-08-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usercsvdownload_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
