# Generated by Django 4.2.14 on 2024-08-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_chatsession_completion_tokens_and_more'),
        ('accounts', '0013_user_interaction_mode_user_voice_speed'),
    ]

    operations = [
    ]
