# Generated by Django 4.2.14 on 2024-08-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_chatmessage_session_alter_chatsession_module_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
