# Generated by Django 4.2.14 on 2024-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_module_is_deleted_task_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
