# Generated by Django 4.2.14 on 2024-09-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='accounts.persona'),
        ),
    ]
