# Generated by Django 4.2.13 on 2024-06-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_module_end_time_remove_module_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('user_message', models.TextField(blank=True, null=True)),
                ('bot_message', models.TextField(blank=True, null=True)),
                ('has_audio', models.BooleanField(default=False)),
                ('audio_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.chatsession')),
            ],
        ),
    ]
