# Generated by Django 4.2.14 on 2024-08-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_chatmessage_session_alter_chatsession_module_and_more'),
        ('langchain_stream', '0002_alter_transcript_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transcripts', to='accounts.chatsession'),
        ),
    ]
